import { useEffect, useState } from "react";
import { Link } from "wouter";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import logoPath from "@assets/s8logov2_clean.png";
import platformImage from "@assets/admin-panel-feature.png";
import {
  ArrowRight,
  Building2,
  CheckCircle,
  GraduationCap,
  HeartHandshake,
  Menu,
  Network,
  Settings,
  ShieldCheck,
  Sparkles,
  Store,
  Trophy,
  Users,
  X,
} from "lucide-react";
import { resetPageSEO, updatePageSEO } from "@/lib/seo";

const partnerLinks = [
  { href: "/#vision", label: "Our Vision" },
  { href: "/#features", label: "Features" },
  { href: "/#pricing", label: "Pricing" },
  { href: "/resources", label: "Resources" },
];

const sectors = [
  { icon: Trophy, label: "Sports clubs & fan communities" },
  { icon: HeartHandshake, label: "Charities & fundraising organisations" },
  { icon: Building2, label: "Businesses & professional networks" },
  { icon: GraduationCap, label: "Education & student communities" },
  { icon: Store, label: "Events & entertainment" },
  { icon: Users, label: "Membership organisations" },
  { icon: Network, label: "Environmental & local community groups" },
  { icon: Sparkles, label: "Hobby & interest groups" },
];

const steps = [
  ["01", "Choose your territory", "Work with Social8 to agree a region or territory where you'll focus your activity."],
  ["02", "Find communities", "Identify organisations, businesses and groups that could benefit from their own Social8 community."],
  ["03", "Launch communities", "Introduce them to Social8 and help them get their community up and running."],
  ["04", "Grow your network", "Continue adding communities and helping them grow and engage their members."],
  ["05", "Earn from your network", "Receive an ongoing share of eligible revenue generated by the communities within your portfolio."],
];

const partnerBenefits = [
  ["Platform", "The technology powering every community.", Settings],
  ["Infrastructure", "Hosting, security and platform maintenance.", ShieldCheck],
  ["Features", "Content, events, polls, quizzes, networking, rewards, payments and more.", Sparkles],
  ["Support", "Ongoing platform support and development.", HeartHandshake],
];

export default function RegionalPartnerPage() {
  const [menuOpen, setMenuOpen] = useState(false);

  useEffect(() => {
    updatePageSEO({
      title: "Become a Social8 Regional Partner | Build Recurring Income",
      description: "Build a portfolio of communities in your region with Social8. Introduce organisations to their own community platform and earn recurring revenue as your network grows.",
      url: "/regional-partner",
      image: platformImage,
    });
    return () => resetPageSEO();
  }, []);

  return (
    <div className="min-h-screen flex flex-col" data-testid="page-regional-partner">
      <header className="sticky top-0 z-50 w-full border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
        <div className="container mx-auto flex h-16 items-center justify-between px-4 gap-4">
          <Link href="/">
            <img src={logoPath} alt="Social8 Logo" className="h-10 object-contain" data-testid="img-logo" />
          </Link>
          <nav className="hidden md:flex items-center gap-6">
            {partnerLinks.map((link) => (
              <Link key={link.href} href={link.href} className="text-sm font-medium text-muted-foreground hover-elevate px-2 py-1 rounded-md">{link.label}</Link>
            ))}
          </nav>
          <div className="flex items-center gap-2">
            <Link href="/create-account"><Button size="sm">Create Account</Button></Link>
            <Button
              size="icon"
              variant="outline"
              className="md:hidden"
              aria-label={menuOpen ? "Close navigation menu" : "Open navigation menu"}
              aria-expanded={menuOpen}
              aria-controls="regional-partner-mobile-navigation"
              data-testid="button-mobile-menu"
              onClick={() => setMenuOpen((open) => !open)}
            >
              {menuOpen ? <X className="w-4 h-4" /> : <Menu className="w-4 h-4" />}
            </Button>
          </div>
        </div>
        {menuOpen && (
          <nav id="regional-partner-mobile-navigation" className="md:hidden border-t bg-background px-4 py-3 grid gap-1">
            {partnerLinks.map((link) => (
              <Link key={link.href} href={link.href} onClick={() => setMenuOpen(false)} className="rounded-md px-3 py-2 text-sm font-medium text-muted-foreground hover:bg-muted">{link.label}</Link>
            ))}
          </nav>
        )}
      </header>

      <main className="flex-1">
        <section className="relative overflow-hidden bg-gradient-to-br from-emerald-600 to-green-700 py-16 lg:py-24 text-white">
          <div className="absolute inset-0 opacity-10 bg-[radial-gradient(circle_at_20%_20%,white_0,transparent_35%),radial-gradient(circle_at_80%_80%,white_0,transparent_35%)]" />
          <div className="container mx-auto px-4 relative">
            <div className="max-w-4xl mx-auto text-center">
              <div className="inline-flex items-center gap-2 rounded-full bg-white/15 px-4 py-2 text-sm font-semibold mb-6">
                <Network className="w-4 h-4" />
                Social8 Regional Partner Programme
              </div>
              <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold leading-tight mb-6">Become a Social8 Regional Partner</h1>
              <p className="text-2xl md:text-3xl text-emerald-50 font-medium mb-6">Build your regional network. Create recurring income.</p>
              <p className="text-lg md:text-xl text-white/90 leading-relaxed max-w-3xl mx-auto mb-8">
                Social8 is looking for ambitious partners to help grow communities across defined regions. Introduce Social8 to organisations in your area and build a portfolio that grows with your network.
              </p>
              <Link href="/contact?type=regional-partner">
                <Button size="lg" variant="secondary" className="gap-2 shadow-lg" data-testid="button-apply-regional-partner">
                  Apply to Become a Regional Partner
                  <ArrowRight className="w-4 h-4" />
                </Button>
              </Link>
            </div>
          </div>
        </section>

        <section className="py-16 lg:py-24">
          <div className="container mx-auto px-4">
            <div className="grid lg:grid-cols-2 gap-12 items-center">
              <div>
                <p className="text-sm font-semibold uppercase tracking-wide text-emerald-700 dark:text-emerald-400 mb-3">What is a Social8 Regional Partner?</p>
                <h2 className="text-3xl md:text-4xl font-bold mb-5">Focus on relationships and growth.</h2>
                <p className="text-lg text-muted-foreground leading-relaxed mb-5">
                  A Regional Partner is responsible for growing the Social8 network within an agreed territory. You identify organisations that could benefit from their own community platform, introduce them to Social8 and help them get started.
                </p>
                <p className="text-lg text-muted-foreground leading-relaxed">
                  Social8 provides the technology, infrastructure and ongoing platform support. You focus on relationships and growth.
                </p>
              </div>
              <div className="relative">
                <div className="absolute inset-0 bg-emerald-300/25 blur-3xl rounded-full scale-75" />
                <img src={platformImage} alt="Social8 platform for managing online communities" className="relative rounded-2xl border shadow-xl w-full" />
              </div>
            </div>
            <div className="mt-14">
              <h2 className="text-2xl font-bold text-center mb-8">You could work with</h2>
              <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">
                {sectors.map(({ icon: SectorIcon, label }) => {
                  return <Card key={label} className="hover-elevate"><CardContent className="p-5 flex items-center gap-3"><SectorIcon className="w-5 h-5 text-emerald-600 dark:text-emerald-400 flex-shrink-0" /><span className="font-medium text-sm">{label}</span></CardContent></Card>;
                })}
              </div>
            </div>
          </div>
        </section>

        <section className="py-16 lg:py-24 bg-muted/30">
          <div className="container mx-auto px-4 max-w-5xl">
            <div className="rounded-3xl border bg-card p-8 md:p-12 shadow-sm">
              <p className="text-sm font-semibold uppercase tracking-wide text-emerald-700 dark:text-emerald-400 mb-3">A different kind of partnership</p>
              <h2 className="text-3xl md:text-4xl font-bold mb-5">Build once. Grow continuously.</h2>
              <p className="text-lg text-muted-foreground leading-relaxed mb-4">You're not just earning commission on a sale. Traditional sales roles often mean finding a customer, making a sale and moving on.</p>
              <p className="text-lg text-muted-foreground leading-relaxed">With Social8, the opportunity is to build a portfolio of communities. As the communities within your network generate revenue, you can receive an ongoing share of that revenue.</p>
            </div>
          </div>
        </section>

        <section className="py-16 lg:py-24">
          <div className="container mx-auto px-4">
            <div className="text-center max-w-3xl mx-auto mb-12">
              <p className="text-sm font-semibold uppercase tracking-wide text-emerald-700 dark:text-emerald-400 mb-3">How it works</p>
              <h2 className="text-3xl md:text-4xl font-bold">Grow your network step by step.</h2>
            </div>
            <div className="grid md:grid-cols-5 gap-4 max-w-6xl mx-auto">
              {steps.map(([number, title, text]) => (
                <div key={number} className="relative text-center" data-testid={`partner-step-${number}`}>
                  <div className="w-12 h-12 rounded-full bg-emerald-600 text-white flex items-center justify-center font-bold mx-auto mb-4">{number}</div>
                  <h3 className="font-semibold mb-2">{title}</h3>
                  <p className="text-sm text-muted-foreground leading-relaxed">{text}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        <section className="py-16 lg:py-24 bg-muted/30">
          <div className="container mx-auto px-4">
            <div className="text-center max-w-3xl mx-auto mb-12">
              <p className="text-sm font-semibold uppercase tracking-wide text-emerald-700 dark:text-emerald-400 mb-3">Your earning potential grows with your network</p>
              <h2 className="text-3xl md:text-4xl font-bold">Build a regional business over time.</h2>
            </div>
            <div className="grid md:grid-cols-3 gap-6 max-w-5xl mx-auto">
              {[
                ["10 Communities", "A starting portfolio"],
                ["25 Communities", "A growing regional business"],
                ["50+ Communities", "A substantial recurring revenue opportunity"],
              ].map(([title, text]) => (
                <Card key={title} className="text-center hover-elevate"><CardContent className="p-8"><div className="text-3xl font-bold text-emerald-700 dark:text-emerald-400 mb-2">{title}</div><p className="text-muted-foreground">{text}</p></CardContent></Card>
              ))}
            </div>
            <p className="text-center text-sm text-muted-foreground max-w-3xl mx-auto mt-8">The exact commercial terms will depend on your territory, partnership structure and the communities you develop. There is no fixed ceiling on the size of your network.</p>
          </div>
        </section>

        <section className="py-16 lg:py-24">
          <div className="container mx-auto px-4">
            <div className="text-center max-w-3xl mx-auto mb-12">
              <p className="text-sm font-semibold uppercase tracking-wide text-emerald-700 dark:text-emerald-400 mb-3">Social8 does the heavy lifting</p>
              <h2 className="text-3xl md:text-4xl font-bold mb-4">You don't need to build or maintain the technology.</h2>
              <p className="text-lg text-muted-foreground">You provide the local relationships, business development and community growth.</p>
            </div>
            <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6 max-w-6xl mx-auto">
              {partnerBenefits.map(([title, text, BenefitIcon]) => {
                return <Card key={title as string} className="h-full hover-elevate"><CardContent className="p-6"><BenefitIcon className="w-7 h-7 text-emerald-600 dark:text-emerald-400 mb-4" /><h3 className="font-semibold text-lg mb-2">{title as string}</h3><p className="text-sm text-muted-foreground leading-relaxed">{text as string}</p></CardContent></Card>;
              })}
            </div>
          </div>
        </section>

        <section className="py-16 lg:py-24 bg-muted/30">
          <div className="container mx-auto px-4">
            <div className="grid lg:grid-cols-2 gap-12 max-w-6xl mx-auto">
              <div>
                <p className="text-sm font-semibold uppercase tracking-wide text-emerald-700 dark:text-emerald-400 mb-3">Who are we looking for?</p>
                <h2 className="text-3xl md:text-4xl font-bold mb-6">People who know their region.</h2>
                <div className="space-y-4">
                  {[
                    "Have strong connections within a particular region or sector",
                    "Enjoy building relationships",
                    "Have business development or sales experience",
                    "Understand local businesses and organisations",
                    "Are entrepreneurial and commercially minded",
                    "Want to build a long-term recurring income opportunity",
                  ].map((item) => <div key={item} className="flex items-start gap-3"><CheckCircle className="w-5 h-5 text-emerald-600 dark:text-emerald-400 flex-shrink-0 mt-0.5" /><span>{item}</span></div>)}
                </div>
                <p className="text-lg text-muted-foreground leading-relaxed mt-7">You don't need to be a technology expert. You need to know people, understand opportunities and be able to open doors.</p>
              </div>
              <div className="rounded-2xl bg-card border p-8">
                <p className="text-sm font-semibold uppercase tracking-wide text-emerald-700 dark:text-emerald-400 mb-3">Why Social8?</p>
                <h2 className="text-2xl md:text-3xl font-bold mb-5">One platform for an entire ecosystem.</h2>
                <p className="text-muted-foreground leading-relaxed mb-4">Social8 gives organisations their own digital community without having to build their own technology.</p>
                <p className="text-muted-foreground leading-relaxed mb-4">One platform can support communities across sports, business, charities, education, memberships, hobbies and more.</p>
                <p className="text-muted-foreground leading-relaxed">For Regional Partners, that means you aren't limited to selling one type of product to one type of customer. You can build an entire ecosystem of communities within your territory.</p>
              </div>
            </div>
          </div>
        </section>

        <section className="py-16 lg:py-20">
          <div className="container mx-auto px-4">
            <div className="relative overflow-hidden rounded-2xl bg-gradient-to-br from-emerald-600 to-green-600 p-8 md:p-12 lg:p-16 text-center text-white">
              <div className="relative max-w-3xl mx-auto">
                <h2 className="text-3xl md:text-4xl lg:text-5xl font-bold mb-4">Ready to build your region?</h2>
                <p className="text-xl text-emerald-50 mb-3">Turn your local network into a long-term business opportunity.</p>
                <p className="text-white/90 mb-8">We're looking for Regional Partners who want to help bring Social8 to new communities and share in the growth.</p>
                <Link href="/contact?type=regional-partner">
                  <Button size="lg" variant="secondary" className="gap-2" data-testid="button-apply-regional-partner-final">
                    Apply to Become a Regional Partner
                    <ArrowRight className="w-4 h-4" />
                  </Button>
                </Link>
                <p className="text-sm text-white/80 mt-5">Already have a region or network in mind? Tell us about it.</p>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}